
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SecondHeader from "./components/secondHeader";
import Footer, { BottomFooter } from "./components/footer";
import ContextProvider from "./contetxtProvider";
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "./provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  


  return (
    <>


{/* <!-- Google tag (gtag.js) --> */}
{/* <script id="usercentrics-cmp" src="https://app.usercentrics.eu/browser-ui/latest/loader.js" data-settings-id="mBc63SwjcPnXjK" async></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LN8RS38BQN"></script>
<script>
  (window as any).dataLayer = (window as any).dataLayer || [];
  function gtag(){(window as any).dataLayer.push(arguments)}
  gtag('js', new Date());

  gtag('config', 'G-LN8RS38BQN');
</script> */}
      {/* Google tag (gtag.js) */}
      {/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-L5JHNJSE0Q"></script>
      <script>
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-L5JHNJSE0Q');
        `}
      </script> */}


     <html lang="en">
      <body className={inter.className}>

      
        <AuthProvider> 
        <ContextProvider> 
        {/* <TopHeader/> */}
        <SecondHeader/>
        {children}
        </ContextProvider>
        </AuthProvider>
        <Toaster />
        <Footer/>
        <BottomFooter/>
      
        </body>
    </html>
    </>
  );
}





















// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import TopHeader from "./components/topHeader";
// import SecondHeader from "./components/secondHeader";
// import Footer, { BottomFooter } from "./components/footer";
// import ContextProvider from "./contetxtProvider";
// import { Toaster } from "@/components/ui/sonner"
// import { AuthProvider } from "./provider/provider";
// import { headers } from "next/headers";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
  






//   return (


//      <html lang="en">
//       <body className={inter.className}>

      
//         <AuthProvider> 
//         <ContextProvider> 
//         {/* <TopHeader/> */}
//         <SecondHeader/>
//         {children}
//         </ContextProvider>
//         </AuthProvider>
//         <Toaster />
//         <Footer/>
//         <BottomFooter/>
      
//         </body>
//     </html>
   
//   );
// }
