import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "./components/topHeader";
import SecondHeader from "./components/secondHeader";
import Footer, { BottomFooter } from "./components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopHeader/>
        <SecondHeader/>
        {children}
        <Footer/>
        <BottomFooter/>
        </body>
    </html>
  );
}
